#! /bin/bash

# Author: Vien Nguye
# Date Created: 04/28/2025
# Last Modified: 04/28/2025
# Description: Create a backup_script which backup all the files in your home directory

# Usage:
# backup_script
tar -cvf ~/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
exit 0
